language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  - sudo apt-get install libdiscid0

install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis

script:
  - tox
  - coverage run -m py.test
  - coverage report -m

after_success:
  - coveralls
