language: python
python:
  - '3.5'
  - '3.6'

before_install:
  - sudo apt-get install libdiscid0

install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile travis-tox

script:
  - pipenv run tox
  - pipenv run coverage run -m py.test
  - pipenv run coverage report -m

after_success:
  - pipenv run coveralls

notifications:
  email: false
